language: generic

matrix:
  include:
    - os: linux
      name: Linux Trusty
      dist: trusty
      sudo: required
    - os: osx
      name: macOS
      osx_image: xcode9.4

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
      swiftenv install 4.1;
      swiftenv local 4.1;
    fi
  - swift --version

script:
  - swift test --parallel
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift package generate-xcodeproj --enable-code-coverage;
      xcodebuild -scheme CommandRegistry-Package test;
    fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi
