language: generic

jobs:
  include:
    - stage: Continuous Integration
      name: Linux Swift 5.0
      os: linux
      dist: trusty
      sudo: required
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - swiftenv install 5.0
      - swiftenv local 5.0
      - swift --version
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: Linux Swift 5.1
      os: linux
      dist: trusty
      sudo: required
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - swiftenv install 5.1
      - swiftenv local 5.1
      - swift --version
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: macOS Swift 5.0
      os: osx
      osx_image: xcode10.3
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: macOS Swift 5.0
      os: osx
      osx_image: xcode103
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: macOS Swift 5.1
      os: osx
      osx_image: xcode10
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: macOS Swift 5.0
      os: osx
      osx_image: xcode11
      script:
      - swift test --parallel
    - stage: Continuous Integration
      name: TestTool Tests
      os: osx
      osx_image: xcode10
      script:
      - cd Tests/TestTool && swift test
    - stage: Continuous Integration
      name: Code Coverage (Swift 5.0)
      os: osx
      osx_image: xcode9.3
      script:
      - swift package generate-xcodeproj --enable-code-coverage
      - xcodebuild -scheme CommandRegistry-Package test
      after_success:
      - bash <(curl -s https://codecov.io/bash)
